# 弃用，使用 metacontroller 自动生成
apiVersion: v1
kind: Service
metadata:
  name: game-server-external
  annotations:
    service.kubernetes.io/tke-existed-lbid: lb-5uh4xaz1  # 使用已创建好的 clb 实例
    service.kubernetes.io/qcloud-share-existed-lb: "true"
spec:
  ports:
    - port: 33000
      targetPort: 8001
      protocol: TCP
  selector:
    app: game-server
  type: LoadBalancer