apiVersion: v1
kind: Service
metadata:
  name: game-server-external
  annotations:
    service.kubernetes.io/tke-existed-lbid: lb-5uh4xaz1  # 使用已创建好的 clb 实例
spec:
  ports:
    - port: 32004
      targetPort: 8001
      protocol: TCP
  selector:
    app: game-server
  type: LoadBalancer