// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: unicast.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Unicast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnicastCode          UnicastCode           `protobuf:"varint,1,opt,name=unicastCode,proto3,enum=proto.UnicastCode" json:"unicastCode,omitempty"`
	HeroFrameSyncUnicast *HeroFrameSyncUnicast `protobuf:"bytes,2,opt,name=heroFrameSyncUnicast,proto3" json:"heroFrameSyncUnicast,omitempty"`
}

func (x *Unicast) Reset() {
	*x = Unicast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unicast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unicast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unicast) ProtoMessage() {}

func (x *Unicast) ProtoReflect() protoreflect.Message {
	mi := &file_unicast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unicast.ProtoReflect.Descriptor instead.
func (*Unicast) Descriptor() ([]byte, []int) {
	return file_unicast_proto_rawDescGZIP(), []int{0}
}

func (x *Unicast) GetUnicastCode() UnicastCode {
	if x != nil {
		return x.UnicastCode
	}
	return UnicastCode_HeroFrameSyncUnicastCode
}

func (x *Unicast) GetHeroFrameSyncUnicast() *HeroFrameSyncUnicast {
	if x != nil {
		return x.HeroFrameSyncUnicast
	}
	return nil
}

type HeroFrameSyncUnicast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movement map[int32]*HeroMovementChangeBroadcast `protobuf:"bytes,1,rep,name=movement,proto3" json:"movement,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //当前视野内的玩家的运动状态+当前位置+服务器发送包的时间
}

func (x *HeroFrameSyncUnicast) Reset() {
	*x = HeroFrameSyncUnicast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unicast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroFrameSyncUnicast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroFrameSyncUnicast) ProtoMessage() {}

func (x *HeroFrameSyncUnicast) ProtoReflect() protoreflect.Message {
	mi := &file_unicast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroFrameSyncUnicast.ProtoReflect.Descriptor instead.
func (*HeroFrameSyncUnicast) Descriptor() ([]byte, []int) {
	return file_unicast_proto_rawDescGZIP(), []int{1}
}

func (x *HeroFrameSyncUnicast) GetMovement() map[int32]*HeroMovementChangeBroadcast {
	if x != nil {
		return x.Movement
	}
	return nil
}

var File_unicast_proto protoreflect.FileDescriptor

var file_unicast_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x07, 0x55, 0x6e, 0x69, 0x63, 0x61, 0x73,
	0x74, 0x12, 0x34, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x4f, 0x0a, 0x14, 0x68, 0x65, 0x72, 0x6f, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65,
	0x72, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x6e, 0x69, 0x63, 0x61,
	0x73, 0x74, 0x52, 0x14, 0x68, 0x65, 0x72, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x79, 0x6e,
	0x63, 0x55, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x22, 0xbe, 0x01, 0x0a, 0x14, 0x48, 0x65, 0x72,
	0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x6e, 0x69, 0x63, 0x61, 0x73,
	0x74, 0x12, 0x45, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08,
	0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x5f, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unicast_proto_rawDescOnce sync.Once
	file_unicast_proto_rawDescData = file_unicast_proto_rawDesc
)

func file_unicast_proto_rawDescGZIP() []byte {
	file_unicast_proto_rawDescOnce.Do(func() {
		file_unicast_proto_rawDescData = protoimpl.X.CompressGZIP(file_unicast_proto_rawDescData)
	})
	return file_unicast_proto_rawDescData
}

var file_unicast_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_unicast_proto_goTypes = []interface{}{
	(*Unicast)(nil),                     // 0: proto.Unicast
	(*HeroFrameSyncUnicast)(nil),        // 1: proto.HeroFrameSyncUnicast
	nil,                                 // 2: proto.HeroFrameSyncUnicast.MovementEntry
	(UnicastCode)(0),                    // 3: proto.UnicastCode
	(*HeroMovementChangeBroadcast)(nil), // 4: proto.HeroMovementChangeBroadcast
}
var file_unicast_proto_depIdxs = []int32{
	3, // 0: proto.Unicast.unicastCode:type_name -> proto.UnicastCode
	1, // 1: proto.Unicast.heroFrameSyncUnicast:type_name -> proto.HeroFrameSyncUnicast
	2, // 2: proto.HeroFrameSyncUnicast.movement:type_name -> proto.HeroFrameSyncUnicast.MovementEntry
	4, // 3: proto.HeroFrameSyncUnicast.MovementEntry.value:type_name -> proto.HeroMovementChangeBroadcast
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_unicast_proto_init() }
func file_unicast_proto_init() {
	if File_unicast_proto != nil {
		return
	}
	file_consts_proto_init()
	file_broadcast_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_unicast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unicast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unicast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroFrameSyncUnicast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unicast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unicast_proto_goTypes,
		DependencyIndexes: file_unicast_proto_depIdxs,
		MessageInfos:      file_unicast_proto_msgTypes,
	}.Build()
	File_unicast_proto = out.File
	file_unicast_proto_rawDesc = nil
	file_unicast_proto_goTypes = nil
	file_unicast_proto_depIdxs = nil
}
