// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: broadcast.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Broadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BroadcastCode               BroadcastCode                `protobuf:"varint,1,opt,name=broadcastCode,proto3,enum=proto.BroadcastCode" json:"broadcastCode,omitempty"`
	HeroChangeHealthBroadcast   *HeroChangeHealthBroadcast   `protobuf:"bytes,2,opt,name=heroChangeHealthBroadcast,proto3" json:"heroChangeHealthBroadcast,omitempty"`
	HeroMovementChangeBroadcast *HeroMovementChangeBroadcast `protobuf:"bytes,3,opt,name=heroMovementChangeBroadcast,proto3" json:"heroMovementChangeBroadcast,omitempty"`
	HeroPositionReportBroadcast *HeroPositionReportBroadcast `protobuf:"bytes,4,opt,name=heroPositionReportBroadcast,proto3" json:"heroPositionReportBroadcast,omitempty"`
	HeroPropDeleteBroadcast     *HeroPropDeleteBroadcast     `protobuf:"bytes,5,opt,name=heroPropDeleteBroadcast,proto3" json:"heroPropDeleteBroadcast,omitempty"`
	HeroPropAddBroadcast        *HeroPropAddBroadcast        `protobuf:"bytes,6,opt,name=heroPropAddBroadcast,proto3" json:"heroPropAddBroadcast,omitempty"`
	HeroAttackBroadcast         *HeroAttackBroadcast         `protobuf:"bytes,7,opt,name=heroAttackBroadcast,proto3" json:"heroAttackBroadcast,omitempty"`
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *Broadcast) GetBroadcastCode() BroadcastCode {
	if x != nil {
		return x.BroadcastCode
	}
	return BroadcastCode_HeroChangeHealthBroadcastCode
}

func (x *Broadcast) GetHeroChangeHealthBroadcast() *HeroChangeHealthBroadcast {
	if x != nil {
		return x.HeroChangeHealthBroadcast
	}
	return nil
}

func (x *Broadcast) GetHeroMovementChangeBroadcast() *HeroMovementChangeBroadcast {
	if x != nil {
		return x.HeroMovementChangeBroadcast
	}
	return nil
}

func (x *Broadcast) GetHeroPositionReportBroadcast() *HeroPositionReportBroadcast {
	if x != nil {
		return x.HeroPositionReportBroadcast
	}
	return nil
}

func (x *Broadcast) GetHeroPropDeleteBroadcast() *HeroPropDeleteBroadcast {
	if x != nil {
		return x.HeroPropDeleteBroadcast
	}
	return nil
}

func (x *Broadcast) GetHeroPropAddBroadcast() *HeroPropAddBroadcast {
	if x != nil {
		return x.HeroPropAddBroadcast
	}
	return nil
}

func (x *Broadcast) GetHeroAttackBroadcast() *HeroAttackBroadcast {
	if x != nil {
		return x.HeroAttackBroadcast
	}
	return nil
}

type HeroChangeHealthBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId     int32 `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	HeroHealth int32 `protobuf:"varint,2,opt,name=heroHealth,proto3" json:"heroHealth,omitempty"`
}

func (x *HeroChangeHealthBroadcast) Reset() {
	*x = HeroChangeHealthBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroChangeHealthBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroChangeHealthBroadcast) ProtoMessage() {}

func (x *HeroChangeHealthBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroChangeHealthBroadcast.ProtoReflect.Descriptor instead.
func (*HeroChangeHealthBroadcast) Descriptor() ([]byte, []int) {
	return file_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *HeroChangeHealthBroadcast) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroChangeHealthBroadcast) GetHeroHealth() int32 {
	if x != nil {
		return x.HeroHealth
	}
	return 0
}

type HeroMovementChangeBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId     int32 `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	HeroHealth int32 `protobuf:"varint,2,opt,name=heroHealth,proto3" json:"heroHealth,omitempty"`
}

func (x *HeroMovementChangeBroadcast) Reset() {
	*x = HeroMovementChangeBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroMovementChangeBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroMovementChangeBroadcast) ProtoMessage() {}

func (x *HeroMovementChangeBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroMovementChangeBroadcast.ProtoReflect.Descriptor instead.
func (*HeroMovementChangeBroadcast) Descriptor() ([]byte, []int) {
	return file_broadcast_proto_rawDescGZIP(), []int{2}
}

func (x *HeroMovementChangeBroadcast) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroMovementChangeBroadcast) GetHeroHealth() int32 {
	if x != nil {
		return x.HeroHealth
	}
	return 0
}

type HeroPositionReportBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId       int32    `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	HeroPosition *Vector2 `protobuf:"bytes,2,opt,name=heroPosition,proto3" json:"heroPosition,omitempty"`
}

func (x *HeroPositionReportBroadcast) Reset() {
	*x = HeroPositionReportBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroPositionReportBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroPositionReportBroadcast) ProtoMessage() {}

func (x *HeroPositionReportBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroPositionReportBroadcast.ProtoReflect.Descriptor instead.
func (*HeroPositionReportBroadcast) Descriptor() ([]byte, []int) {
	return file_broadcast_proto_rawDescGZIP(), []int{3}
}

func (x *HeroPositionReportBroadcast) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroPositionReportBroadcast) GetHeroPosition() *Vector2 {
	if x != nil {
		return x.HeroPosition
	}
	return nil
}

type HeroPropDeleteBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropId int32 `protobuf:"varint,1,opt,name=propId,proto3" json:"propId,omitempty"`
}

func (x *HeroPropDeleteBroadcast) Reset() {
	*x = HeroPropDeleteBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroPropDeleteBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroPropDeleteBroadcast) ProtoMessage() {}

func (x *HeroPropDeleteBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroPropDeleteBroadcast.ProtoReflect.Descriptor instead.
func (*HeroPropDeleteBroadcast) Descriptor() ([]byte, []int) {
	return file_broadcast_proto_rawDescGZIP(), []int{4}
}

func (x *HeroPropDeleteBroadcast) GetPropId() int32 {
	if x != nil {
		return x.PropId
	}
	return 0
}

type HeroPropAddBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropId       int32    `protobuf:"varint,1,opt,name=propId,proto3" json:"propId,omitempty"`
	PropPosition *Vector2 `protobuf:"bytes,2,opt,name=propPosition,proto3" json:"propPosition,omitempty"`
}

func (x *HeroPropAddBroadcast) Reset() {
	*x = HeroPropAddBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroPropAddBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroPropAddBroadcast) ProtoMessage() {}

func (x *HeroPropAddBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroPropAddBroadcast.ProtoReflect.Descriptor instead.
func (*HeroPropAddBroadcast) Descriptor() ([]byte, []int) {
	return file_broadcast_proto_rawDescGZIP(), []int{5}
}

func (x *HeroPropAddBroadcast) GetPropId() int32 {
	if x != nil {
		return x.PropId
	}
	return 0
}

func (x *HeroPropAddBroadcast) GetPropPosition() *Vector2 {
	if x != nil {
		return x.PropPosition
	}
	return nil
}

type HeroAttackBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId         int32          `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	HeroAttackType HeroAttackType `protobuf:"varint,2,opt,name=heroAttackType,proto3,enum=proto.HeroAttackType" json:"heroAttackType,omitempty"`
	Position       *Vector2       `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Direction      *Vector2       `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *HeroAttackBroadcast) Reset() {
	*x = HeroAttackBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroAttackBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroAttackBroadcast) ProtoMessage() {}

func (x *HeroAttackBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroAttackBroadcast.ProtoReflect.Descriptor instead.
func (*HeroAttackBroadcast) Descriptor() ([]byte, []int) {
	return file_broadcast_proto_rawDescGZIP(), []int{6}
}

func (x *HeroAttackBroadcast) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroAttackBroadcast) GetHeroAttackType() HeroAttackType {
	if x != nil {
		return x.HeroAttackType
	}
	return HeroAttackType_HeroSwordAttackType
}

func (x *HeroAttackBroadcast) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *HeroAttackBroadcast) GetDirection() *Vector2 {
	if x != nil {
		return x.Direction
	}
	return nil
}

type GameStartBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId int32 `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"` //没啥用
}

func (x *GameStartBroadcast) Reset() {
	*x = GameStartBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broadcast_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStartBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartBroadcast) ProtoMessage() {}

func (x *GameStartBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartBroadcast.ProtoReflect.Descriptor instead.
func (*GameStartBroadcast) Descriptor() ([]byte, []int) {
	return file_broadcast_proto_rawDescGZIP(), []int{7}
}

func (x *GameStartBroadcast) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

var File_broadcast_proto protoreflect.FileDescriptor

var file_broadcast_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x04, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0d, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x0d, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x5e,
	0x0a, 0x19, 0x68, 0x65, 0x72, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x52, 0x19, 0x68, 0x65, 0x72, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x64,
	0x0a, 0x1b, 0x68, 0x65, 0x72, 0x6f, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f,
	0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x1b, 0x68, 0x65, 0x72, 0x6f, 0x4d, 0x6f, 0x76,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x12, 0x64, 0x0a, 0x1b, 0x68, 0x65, 0x72, 0x6f, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x1b, 0x68,
	0x65, 0x72, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x58, 0x0a, 0x17, 0x68, 0x65,
	0x72, 0x6f, 0x50, 0x72, 0x6f, 0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x50, 0x72, 0x6f, 0x70, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x17, 0x68, 0x65, 0x72,
	0x6f, 0x50, 0x72, 0x6f, 0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x14, 0x68, 0x65, 0x72, 0x6f, 0x50, 0x72, 0x6f, 0x70,
	0x41, 0x64, 0x64, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x50,
	0x72, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52,
	0x14, 0x68, 0x65, 0x72, 0x6f, 0x50, 0x72, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x13, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x6b, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x6b, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x13,
	0x68, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x22, 0x53, 0x0a, 0x19, 0x48, 0x65, 0x72, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x65,
	0x72, 0x6f, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x55, 0x0a, 0x1b, 0x48, 0x65, 0x72, 0x6f,
	0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22,
	0x69, 0x0a, 0x1b, 0x48, 0x65, 0x72, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x0c, 0x68, 0x65, 0x72, 0x6f, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x52, 0x0c, 0x68, 0x65,
	0x72, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x17, 0x48, 0x65,
	0x72, 0x6f, 0x50, 0x72, 0x6f, 0x70, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x62, 0x0a,
	0x14, 0x48, 0x65, 0x72, 0x6f, 0x50, 0x72, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x32, 0x0a,
	0x0c, 0x70, 0x72, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x32, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xc6, 0x01, 0x0a, 0x13, 0x48, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72,
	0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49,
	0x64, 0x12, 0x3d, 0x0a, 0x0e, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0e, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x32, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x52,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_broadcast_proto_rawDescOnce sync.Once
	file_broadcast_proto_rawDescData = file_broadcast_proto_rawDesc
)

func file_broadcast_proto_rawDescGZIP() []byte {
	file_broadcast_proto_rawDescOnce.Do(func() {
		file_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(file_broadcast_proto_rawDescData)
	})
	return file_broadcast_proto_rawDescData
}

var file_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_broadcast_proto_goTypes = []interface{}{
	(*Broadcast)(nil),                   // 0: proto.Broadcast
	(*HeroChangeHealthBroadcast)(nil),   // 1: proto.HeroChangeHealthBroadcast
	(*HeroMovementChangeBroadcast)(nil), // 2: proto.HeroMovementChangeBroadcast
	(*HeroPositionReportBroadcast)(nil), // 3: proto.HeroPositionReportBroadcast
	(*HeroPropDeleteBroadcast)(nil),     // 4: proto.HeroPropDeleteBroadcast
	(*HeroPropAddBroadcast)(nil),        // 5: proto.HeroPropAddBroadcast
	(*HeroAttackBroadcast)(nil),         // 6: proto.HeroAttackBroadcast
	(*GameStartBroadcast)(nil),          // 7: proto.GameStartBroadcast
	(BroadcastCode)(0),                  // 8: proto.BroadcastCode
	(*Vector2)(nil),                     // 9: proto.Vector2
	(HeroAttackType)(0),                 // 10: proto.HeroAttackType
}
var file_broadcast_proto_depIdxs = []int32{
	8,  // 0: proto.Broadcast.broadcastCode:type_name -> proto.BroadcastCode
	1,  // 1: proto.Broadcast.heroChangeHealthBroadcast:type_name -> proto.HeroChangeHealthBroadcast
	2,  // 2: proto.Broadcast.heroMovementChangeBroadcast:type_name -> proto.HeroMovementChangeBroadcast
	3,  // 3: proto.Broadcast.heroPositionReportBroadcast:type_name -> proto.HeroPositionReportBroadcast
	4,  // 4: proto.Broadcast.heroPropDeleteBroadcast:type_name -> proto.HeroPropDeleteBroadcast
	5,  // 5: proto.Broadcast.heroPropAddBroadcast:type_name -> proto.HeroPropAddBroadcast
	6,  // 6: proto.Broadcast.heroAttackBroadcast:type_name -> proto.HeroAttackBroadcast
	9,  // 7: proto.HeroPositionReportBroadcast.heroPosition:type_name -> proto.Vector2
	9,  // 8: proto.HeroPropAddBroadcast.propPosition:type_name -> proto.Vector2
	10, // 9: proto.HeroAttackBroadcast.heroAttackType:type_name -> proto.HeroAttackType
	9,  // 10: proto.HeroAttackBroadcast.position:type_name -> proto.Vector2
	9,  // 11: proto.HeroAttackBroadcast.direction:type_name -> proto.Vector2
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_broadcast_proto_init() }
func file_broadcast_proto_init() {
	if File_broadcast_proto != nil {
		return
	}
	file_consts_proto_init()
	file_struct_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_broadcast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Broadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroChangeHealthBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroMovementChangeBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroPositionReportBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroPropDeleteBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroPropAddBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroAttackBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broadcast_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStartBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_broadcast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_broadcast_proto_goTypes,
		DependencyIndexes: file_broadcast_proto_depIdxs,
		MessageInfos:      file_broadcast_proto_msgTypes,
	}.Build()
	File_broadcast_proto = out.File
	file_broadcast_proto_rawDesc = nil
	file_broadcast_proto_goTypes = nil
	file_broadcast_proto_depIdxs = nil
}
