// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: unicast.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Unicast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnicastCode UnicastCode `protobuf:"varint,1,opt,name=unicastCode,proto3,enum=proto.UnicastCode" json:"unicastCode,omitempty"`
}

func (x *Unicast) Reset() {
	*x = Unicast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unicast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unicast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unicast) ProtoMessage() {}

func (x *Unicast) ProtoReflect() protoreflect.Message {
	mi := &file_unicast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unicast.ProtoReflect.Descriptor instead.
func (*Unicast) Descriptor() ([]byte, []int) {
	return file_unicast_proto_rawDescGZIP(), []int{0}
}

func (x *Unicast) GetUnicastCode() UnicastCode {
	if x != nil {
		return x.UnicastCode
	}
	return UnicastCode_Temp
}

var File_unicast_proto protoreflect.FileDescriptor

var file_unicast_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x07, 0x55, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x12,
	0x34, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x6e, 0x69,
	0x63, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x73,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unicast_proto_rawDescOnce sync.Once
	file_unicast_proto_rawDescData = file_unicast_proto_rawDesc
)

func file_unicast_proto_rawDescGZIP() []byte {
	file_unicast_proto_rawDescOnce.Do(func() {
		file_unicast_proto_rawDescData = protoimpl.X.CompressGZIP(file_unicast_proto_rawDescData)
	})
	return file_unicast_proto_rawDescData
}

var file_unicast_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_unicast_proto_goTypes = []interface{}{
	(*Unicast)(nil),  // 0: proto.Unicast
	(UnicastCode)(0), // 1: proto.UnicastCode
}
var file_unicast_proto_depIdxs = []int32{
	1, // 0: proto.Unicast.unicastCode:type_name -> proto.UnicastCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_unicast_proto_init() }
func file_unicast_proto_init() {
	if File_unicast_proto != nil {
		return
	}
	file_consts_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_unicast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unicast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unicast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unicast_proto_goTypes,
		DependencyIndexes: file_unicast_proto_depIdxs,
		MessageInfos:      file_unicast_proto_msgTypes,
	}.Build()
	File_unicast_proto = out.File
	file_unicast_proto_rawDesc = nil
	file_unicast_proto_goTypes = nil
	file_unicast_proto_depIdxs = nil
}
